config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    
    resources :tasks, only: [:create,:destroy]
    
  end

resource :login
  
  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :title, presence: {message:"Sorry,can't be blank....."}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title,presence: true
  scope :unfinished, -> { where(done: false)}
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
  protect_from_forgery

  def current_user
    if session[:user_id]
      # @current_userがnilかfalseならログインユーザーを代入
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user
end

app/controllers/logins_controller.rb
# -*- coding: utf-8 -*-
class LoginsController < ApplicationController
  def show
    render "new"
  end
  
  def create
    user = User.find_by_name params[:name]
    if user && user.authenticate(params[:pass])
      
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = "もう一度入力してください。"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to login_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:show, :edit, :destroy, :update]
  
  def index
    @projects = Project.all
  end
  
  def show
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else 
      render "new"		
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @project.destroy
    redirect_to projects_path
  end
  
  private
  
  def project_params
    params[:project].permit(:title)
  end
  
  def set_project
    @project = Project.find(params[:id])
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    render nothing: true
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end
  
  private
  
  def task_params
    params[:task].permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
# -*- coding: utf-8 -*-
module ProjectsHelper

def caution_disp(task_count =0)

 if task_count == 0 then
 "よく頑張りました！少し休憩するのはいかがでしょうか"
 elsif task_count <= 3 then
 "もう少しです、頑張りましょう"
 elsif task_count <= 7 then
 "ちょっと焦りましょう"
 else
 "さすがにやべえぞ、はよやれ"
 end

end
 
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "mylog.png",:size => '200x250' %>

<%= yield %>

<%= link_to "Home","/" %> 
</body>
</html>

app/views/logins/new.html.erb
<h1>ログイン画面</h1>

<!-- フラッシュ変数のメッセージを表示（ログインエラー時のみ） -->
<p><font color=red><%= flash[:alert] %></font></p>
<%= form_tag login_path do %>
<table id="login_form">
  <tr>
    <td><%= label_tag :name, 'ユーザー名' %></td>
    <td><%= text_field_tag :name, params[:name] %></td>
  </tr>

  <tr>
    <td><%= label_tag :pass, 'パスワード' %></td>
    <td><%= password_field_tag :pass, params[:pass] %></td>
  </tr>

  <tr>
    <td><%= submit_tag "ログイン" %></td>
  </tr>
</table>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <% if @project.errors.any? %>
  <%= @project.errors.messages[:title][0] %>
  <% end %> 
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if current_user == nil %>
  <%= button_to "ログイン", login_path %>
<% else %>
  <%= button_to "ログアウト", login_path, :confirm => "ログアウトしますか？", :method => :delete %>
<% end %>

<ul>
<% unfinished_task = 0 %>
  <% @projects.each do |project| %>
  <li>
    <%= link_to project.title, project_path(project.id)%>(<%= project.tasks.unfinished.count %>/<%= project.tasks.count %>)
    <%= link_to "[Edit]",edit_project_path(project.id) %>
    <%= link_to "[Delete]",project_path(project.id), method: :delete,data:{confirm:"are you sure?"}  %>
  </li>
<% unfinished_task += project.tasks.unfinished.count %>
  <% end %>
</ul>

<p> 現在あなたが溜め込んでいるタスクは<%= unfinished_task %>個です。</p>

<strong><p><%= caution_disp(unfinished_task)%></p></strong>

<p><%= link_to "新しいプロジェクトを追加する。", new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul>
  <% @project.tasks.each do |task|  %>
  <li>
    <%= check_box_tag '','',task.done,{'data-id' => task.id,'data-project_id' => task.project_id} %>
    <%= task.title %>
    <%= link_to "[Delete]",project_task_path(task.project_id,task.id), method: :delete,data:{confirm:"are you sure?"}  %>
  </li>
  <% end %>
  
  <li>
    <%= form_for [@project,@project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
    <% end %>
  </li>
</ul>

<script>
  $(function(){
  $("input[type=checkbox]").click(function(){
  $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
  });
});
</script>